# NOTE: This workflow pushes to a private DockerHub repo
name: Build and push image to DockerHub

on:
    push:
        branches:
        -   main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4
            with:
                submodules: recursive
                token: ${{ secrets.CLIMATE_DB_DATA_PAT }}

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Build and push
            uses: docker/build-push-action@v6
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/us-climate-emotions-map:nightly
